### ISSUE TITLE
Cannot read property includes of undefined

### ISSUE THREAD

**Issue by mschwartz** [jvmahon/homebridge-hubitat#11]
I am getting this error, UnhandledPromiseRejectionWarning, for every virtual switch and physical button I have on my hub.

a try/catch around this code might be a good idea 👍 

Thanks for this.

**Comment by jvmahon** [comment]
Virtual switches should work, but physical buttons aren't generally supported (its a homekit limitation).
Rather than just do try/catch, I'd like to look a bit closer at the error itself -- at least in the case of virtual switches, I might be able to add support.

Can you tell me how you set up these virtual switches (i.e., what driver, etc.) so I can try and recreate / correct the error.

As for the buttons, the best way to handle that may be to not include them in the MakerAPI list - but, again, if I knew more aobut what was happening, I might be able to fix.

**Comment by mschwartz** [comment]
I just added virtual switches in the Hubitat page.

I am merely suggesting that the plug-in not throw untaught exceptions.  The try/catch should just ignore devices/types it can’t grok.  I would be satisfied with the plug-in limping along instead of failing or forcing me to remove devices from my hub...

Cheers

**Comment by jvmahon** [comment]
Can you please let me know which driver you used for the virtual switches.
I'm find with adding some try / catch to the code, but I also want to see why there is an error. Virtual switches should work.

**Comment by mschwartz** [comment]
I created a virtual switch using the hubitat UI in the browser.  Plain old switch, nothing special.  I didn’t choose any drivers.  It’s built in to hubitat.

I created a virtual switch for the TV in my home office.  I monitor the state of the TV using a Node JS program that runs all the time.  If I turn in the TV with the remote, the node program sees it is on and uses the Maker API to turn on the virtual switch.  Same thing for off.  If the virtual switch is turned on, the node js program sees that and turns on the TV.  Etc.

It also allows me to use the hubitat Alexa and Google home integration.  So I can say “Alexa p, turn on the office TV” (which turns on the virtual switch, thanks hubitat) and the node program turns on the TV.  It’s really easy to get that going.

Making Siri able to turn on and off the TV is tricky because there is no hubitat integration.  Thus the need for HomeKit...

**Comment by jvmahon** [comment]
The problem I'm addressing is that, when I make a virtual switch, it works fine.

Even when setting up a virtual switch, you pick some driver - for mine, I choose "Generic Component Switch" - I'm asking what you chose so I can replicate the issue.  Please take another look at your virtual switch and tell me what is in your "Type" field for the switch - see image, below.

![image](https://user-images.githubusercontent.com/15061942/101267403-43295800-3726-11eb-945e-6a9240955b8f.png)

**Comment by mschwartz** [comment]
![2020-12-05 at 4 35 PM](https://user-images.githubusercontent.com/329637/101268463-f179d100-3717-11eb-81e5-90f1d317be08.png)

**Comment by jvmahon** [comment]
Thank you! I'll check it out sometime this week.

**Comment by jvmahon** [comment]
Still can't reproduce the error with the virtual switch -- it must be the button devices.

Can you send me info showing the Type for the button devices, as you did above for the virtual switch.

Button-only devices aren't supported, so I'll work the code to make sure they give an appropriate error message.

**Comment by mschwartz** [comment]
I only had one button added to my HE.  I was testing it out.  I removed it when this error occurred.  It didn't fix things, but the error didn't occur while trying tp process the button anymore.  The error then occurred on the virtual switches.  I removed one and the error occurred on the next switch...

**Comment by mschwartz** [comment]
https://stackshare.io/exception-monitoring

We use(d) things like these to track exceptions thrown in our applications that are widely in use.

FWIW

**Comment by jvmahon** [comment]
Thanks. Unforrtunately, without knowing more about the exception message, its pretty difficult for me to figure out where I need to add the try / catch. If you encounter the exception again, please post the full error message so I know which code module to check into. Thanks.

**Comment by jvmahon** [comment]
If the issue re-emerges, please re-open this comment and past the full error message.
