### ISSUE TITLE
"homebridge-hubitat is taking a long time to load and preventing Homebridge from starting"

### ISSUE THREAD

**Issue by AndrewMorsillo** [jvmahon/homebridge-hubitat#14]
Unfortunately there's no other information in the logs. The server restarted on a reboot of my computer and how is hung by the hubitat plugin with "homebridge-hubitat is taking a long time to load and preventing Homebridge from starting"

Homebridge 1.3.0-beta.33
Node 12.18.3
homebridge-hubitat 1.0.2

**Comment by jvmahon** [comment]
Try shutting down both homebridge as well as hubitat. Then restart hubitat first, give it a minute or two, then restart homebridge.

The only other thing to suggest - I think I also encoutered problems with the homebridge beta and you may have to go back to the release version, 1.1.7.

**Comment by AndrewMorsillo** [comment]
It randomly started working again after a few restarts *shrug*. Not sure what was going on but it's fine now.
