### ISSUE TITLE
Feature request: WindowCovering

### ISSUE THREAD

**Issue by mbaastrup** [jvmahon/homebridge-hubitat#15]
With reference to your Homeseer4 platform, the same window covering HK support would be appreciated.

**Comment by jvmahon** [comment]
No problem. I should have this added before the weekend.

**Comment by mbaastrup** [comment]
Awesome! Thanks!

/MB

**Comment by jvmahon** [comment]
I released an update - its untested since I don't have window shades on hubitat, but once you try it out, re-open the issue if there are problems. Thanks.

**Comment by mbaastrup** [comment]
Cool! I will test it out when I have the hubitat up and running. 

On the my HS platform the HS-devices for Window and WondowCovering is exactly the same (0=Close;1-98=Pos;99=Open). I would imagine its gonna be the same on Hubitat, but to be seen what will be the better way.
As long as you can set OnValue and OffValue in the HomeBridge config, we can make it work.

Thanks!

/MB
