### ISSUE TITLE
RGBW bulbs won’t change CT

### ISSUE THREAD

**Issue by kfraleigh** [jvmahon/homebridge-hubitat#2]
Just like it sounds. I wasn’t able to control color temperature, but could control color. I don’t have this problem with the Hubitat HubConnect app.

**Comment by jvmahon** [comment]
I was struggling on that one. I need to buy some color bulbs so I can work on this a bit more. For now, I'm still working on other aspects, and then I'll buy some color bulbs.

Thanks!

**Comment by jvmahon** [comment]
By the way, what bulbs are you using?

**Comment by jvmahon** [comment]
Try upgrading to 0.0.8 - this fixes several problems with color bulbs.
