### ISSUE TITLE
Reasonable ranges for thermostats

### ISSUE THREAD

**Issue by drewcovi** [jvmahon/homebridge-hubitat#23]
Noticed the range provided here:

https://github.com/jvmahon/homebridge-hubitat/blob/5b2fcb462fffec930e425b08346f8cfc372503ad/lib/Setup%20Thermostats.js#L105

Any chance we can borrow from `homebridge-nest` to better provide ranges for thermostats?

https://github.com/chrisjshull/homebridge-nest/blob/6428e61c2abb8ee8a9025c4bc277e62958bd9adc/lib/nest-thermostat-accessory.js#L61

Right now, this default range creates a thermostat with a **huge** range, which makes setting the target tough in the UI.

**Comment by jvmahon** [comment]
Yes, that can be changed. It should not be that large.
That's the range I usually use for outdoor thermostats -- must have been carried over from that.

**Comment by jvmahon** [comment]
Try updating to 1.0.11.

**Comment by drewcovi** [comment]
Love it!

**Comment by drewcovi** [comment]
Thanks as always
