### ISSUE TITLE
Configuration menu for Hubitat HSM shows textbox with []

### ISSUE THREAD

**Issue by con40** [jvmahon/homebridge-hubitat#25]
Using HOOBS version 3.3.5 and Node version 14.16.0

Recreate:

1. Install the plugin from the plugin search menu
2. Navigate to configuration > Hubitat 
3.  See the setting named "Create HomeKit Security System Device to Interface to Hubitat HSM" is followed by a text box that only contains the string "[]"

This doesn't match the documentation and I'm uncertain how to enable Hubitat HSM for HomeKit.  Image attahed.
<img width="1141" alt="Screen Shot 2021-06-21 at 8 33 06 PM" src="https://user-images.githubusercontent.com/15898270/122844575-f6772a00-d2cf-11eb-85d9-6e90caebd033.png">

**Comment by jvmahon** [comment]
It looks like you are using an outdated version of the plugin.
You need to do an update
On windows, I'd do:
`````
npm -g update
`````
On linux, this might be done as a "sudo"

Then follow by 
`````
npm -g list --depth=0
`````

the plugin should be version 1.0.11

Sometimes, the update doesn't quite work, in which case, do a full un-install and re-install of the plugin.

**Comment by jvmahon** [comment]
The correct / current setting screen should look like:
![image](https://user-images.githubusercontent.com/15061942/122917887-8480fe00-d32c-11eb-9a9f-5c5045098a2c.png)
