### ISSUE TITLE
Excessive Heartbeat Logging

### ISSUE THREAD

**Issue by cefoster0** [jvmahon/homebridge-hubitat#26]
I love how fast this plugin executes actions, much better than others. However, the amount of logging of 'heartbeat / heartbeat received' seems excessive. Can we only log heartbeat failures? Perhaps make that a config option? 

Thank you!

**Comment by jvmahon** [comment]
The logging is intentional to show that the plugin hasn't lost communication with Hubitat. I suppose it can be changed to only display the message less often.

**Comment by cefoster0** [comment]
yes my suggestion for that message in particular is perhaps have it behind a checkbox. just a suggestion!

**Comment by jvmahon** [comment]
I decided to change this so the message only shows up on a failure.
Update from the config-ui-x interface.

**Comment by cefoster0** [comment]
perfect, thank you!

**Comment by jvmahon** [comment]
Also just found a battery reporting error, so upgrade to 1.0.14.
