### ISSUE TITLE
plugin not loading in my homebridge

### ISSUE THREAD

**Issue by DaveGraham123456** [jvmahon/homebridge-hubitat#28]
ERROR LOADING PLUGIN homebridge-hubitat:
[9/15/2021, 22:24:05] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/homebridge-hubitat/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.

**Comment by jvmahon** [comment]
Be sure to update the plugin to 1.0.20

**Comment by DaveGraham123456** [comment]
You don’t mean homeseer do you? You mean hubitat?

I uninstalled and reinstalled via Homebridge UX

still same error

**Comment by jvmahon** [comment]
Oops. I have versions for both platforms -- I need to update my Hubitat one.

**Comment by jvmahon** [comment]
I just published 1.0.15 which should fix the problem.
`````
npm -g uninstall homebridge-hubitat
npm -g install homebridge-hubitat
`````

**Comment by DaveGraham123456** [comment]
Well, that all seems to work

my zemismart blind is exposed, is says blind, but it renders as a window icon.   I will go check it can move

also, you were very quick, bravo!!

**Comment by jvmahon** [comment]
You can change the icon in the HomeKit app. Take a look at these example guides

https://www.homekitauthority.com/homekit-how-to-guide-004-how-to-change-homekit-icons/

https://www.youtube.com/watch?v=BE3a8s_chXc

**Comment by DaveGraham123456** [comment]
You mis understand me

the first screen shot is my Soma smart blind and the icon choices

![981462FC-D291-4FCE-BA2F-19697F4079AB](https://user-images.githubusercontent.com/68233868/133518528-ada5f2a6-a827-46d2-937d-324d3668673e.png)

the second is the hubitat exposed one from your plugin

it thinks it is a window but appears to function as a blind
![Uploading 7A03F4F0-AD26-452F-8631-C2F378536C9E.png…]()

**Comment by DaveGraham123456** [comment]
![Uploading 0A28A76B-2021-41F7-A180-868919C2F5CC.png…]()

**Comment by DaveGraham123456** [comment]
![90BF2B52-20F3-483A-81CB-E15DA249446B](https://user-images.githubusercontent.com/68233868/133519259-8600e9ec-164d-46b0-8007-799e8592dc3e.jpeg)
Side by side

**Comment by jvmahon** [comment]
This is intentional in my plugin.

Many shades / blinds have only one-way communication (well, at least the ones I own do). What that means is that hubitat and homekit can't be certain of the state the blinds are in (they could be opened from another remote, for example, and Hubitat wouldn't know).  However, I wanted to make sure I could always open or close them from Homekit. My solution was to have the blinds always set at 50%. Thus, I can always swipe up to open them, or swipe down to close them.
