### ISSUE TITLE
I have uninstalled and reinstalled this plugin nearly 10 times and every time I get an error... PLEASE HELP

### ISSUE THREAD

**Issue by mnfctrdinitaly** [jvmahon/homebridge-hubitat#31]
Was working just fine the other day, and then I decided to attempt to fix another plugin which destroyed my entire HB setup. Started anew with a fresh install and can't seem to get past this error... 

<img width="950" alt="Screen Shot 2021-11-28 at 6 52 26 PM" src="https://user-images.githubusercontent.com/95198669/143802673-f6f53769-486d-440b-832a-fa2bc962c495.png">
<img width="938" alt="Screen Shot 2021-11-28 at 8 08 13 PM" src="https://user-images.githubusercontent.com/95198669/143802680-642084b8-db61-4010-af56-594777cdaf25.png">

**Comment by jvmahon** [comment]
This was due to a change in the chalk library.
I just updated the plugin
Update to 1.0.17 and it should be fixed.

`````
npm -g update
`````

**Comment by mnfctrdinitaly** [comment]
You're a life saver! 

My other half was gonna be pissed if the thermostat was no longer available! 

A 24bit thank you!

**Comment by jvmahon** [comment]
You're welcome.   I'll close this comment now.
