### ISSUE TITLE
Homebridge restart defaults Yale lock to "Unlocked"

### ISSUE THREAD

**Issue by Greminn** [jvmahon/homebridge-hubitat#38]
Hi There, I have both Hubitat and homebridge-hubitat updated with the latest versions, I have noticed that when Homebridge restarts, it sets the lock as "Unlocked", even tho its status says locked on Hubitat (physically checked this as well).

**Comment by jvmahon** [comment]
I hadn't noticed that before, but I think it was an easy fix. Try updating to 1.0.25

**Comment by Greminn** [comment]
Looks like that fixed it thanks! Note tho for some reason I had to force close the iPad Home app and open again (I am remote to the house, so that may have something todo with it. Opening the home app on the iPhone showed the door as locked.
