### ISSUE TITLE
Garage door is stuck "open" in homebridge until the first time it's actually opened and closed again

### ISSUE THREAD

**Issue by electric-monk** [jvmahon/homebridge-hubitat#39]
Probably same issue as #38, `setInitialValue` just needs referred to first time.

I did also previously experience #38 but it's indeed fixed by ad609a9961471fd75af3206af17ba13656991ba4

**Comment by jvmahon** [comment]
Ugh. Looking at the code, nothing about the GarageDoor type is correct! Looks like I started implementing it based on a lock but never quite finished.

sorry about that. Should have a fix out within a day.

**Comment by jvmahon** [comment]
Try the plugin update 1.0.26

**Comment by electric-monk** [comment]
Yup, looks like that's fixed it, thanks!
