### ISSUE TITLE
Testers Needed - Thermostats

### ISSUE THREAD

**Issue by jvmahon** [jvmahon/homebridge-hubitat#4]
I think the "Thermostat" code is now working, but testing by users is needed.

If you've tried this out and everything looks OK, can you reply indicating which Thermostat you tested and which HomeSeer driver (built-in, community, etc.). If it isn't working, can you describe the problem in as much detail as you can (what happened, what was expected, log reports (if a cloud-based thermostat control, do you get a message indicating that it was a failure in cloud communication, etc.)

**Comment by drewcovi** [comment]
Works pretty great. I’ve done the Celsius work in homebridge-Vera. Happy to contribute.

**Comment by jvmahon** [comment]
Thanks!  Celsius should be working too - as long as you set up the Temperature Unit for "C" in config-ui-x. Let me know if there's a problem. Thanks.
