### ISSUE TITLE
State of the plugin?

### ISSUE THREAD

**Issue by robacarp** [jvmahon/homebridge-hubitat#41]
Including this one, Hubitat has four homekit integrations:

- The (beta) official integration (doesn't support locks or garage doors)
- The Tonesto one, which implements it's own hubitat side api
- The "hubitat-makerapi" one (danTapps)
- and this, which I've been heretofore unaware of

The other three have drawbacks for me. The official integration apparently won't ever support locks or garage doors. Tonesto is more advanced but I can honestly not get it to work. And both Tonesto and DanTapps appear to have all but abandoned theirs. I've been tolerating various bugs for years because they won't get addressed and they're not annoying _enough_ for me to dive into it -- plus the lack of community maintenance means I'd be taking on my own technical ownership and I don't really want that either.

The recent launch of the official-beta kind of makes things complicated, because the majority of my devices will port over, but some _wont_. So I'm just curious, what's your state of the plugin? You have recent merges, but what's your plan? There's likely a lot of work invested here already! Thank you! 🍰

**Comment by jvmahon** [comment]
This plugin is a port of one that I originally developed for HomeSeer. Functionality, its pretty similar to most of the others, but I think its simpler to set up and the code IMO is a bit cleaner (its much more modular in its implementation).    I tried the official integrated "beta" but its not really ready for my use.  

I view this plugin as "complete" - if you look in Section 4 of the README ("Supported Device Types") you'll see what it supports - I think it is about as complete as HomeKit will allow.

Longer term, it looks like Apple is going full-in on the Matter protocol and is unlikely to add to homeKit (they haven't added much in years), so I don't have any plans for much in the future. I'm hoping to see Hubitat support a hubitat-Matter bridge which would get rid of the need for this plugin entirely. Personally, I don't see why Hubitat decided to add a HomeKit integrated plugin at this time - would have preferred they went straight to a Matter capable plugin, but maybe the step to the HomeKit one was easier or they could have had that under development for a while.

**Comment by robacarp** [comment]
Thank you!
