### ISSUE TITLE
Devices of type Group Bulb Dimmer-2.1 don't update status correctly

### ISSUE THREAD

**Issue by AndrewMorsillo** [jvmahon/homebridge-hubitat#6]
I have several groups of bulbs using the Hubitat built in Group Bulb Dimmer-2.1. These devices don't update in homebridge. They always show as off. I see nothing in the logs about them other than the following:

Initially there's
```
Creating new Accessary with ID:520 labeled Office Lights and a type Group Bulb Dimmer-2.1.
```

Then 

```
Initializing platform accessory 'Office Lights'...
```

and later

```
Queued to device id: 520 labeled Office Lights the command refresh.
```

The status never seems to update until a command is sent to Hubitat to control the device. When that happens the homebridge device updates, but only the property that was changed in Hubitat. For example homebridge will say "office lights, 0%, off", I turn them on via Hubitat, then homebridge says "office lights, 0%, on" even though the real status is "office lights, 100%, on". It only updates the property from the command instead of getting the whole device state.

**Comment by jvmahon** [comment]
Thanks! This happens because hubitat drivers are very inconsistent in how they implement the "refresh" command.

I plan to fix that in the next release by using a different way to establish initial values.

In the meantime, you can always add the lights individually and group them from within iOS.

**Comment by jvmahon** [comment]
Try updating to version 0.0.8 and let me know if that fixes the problem.
`````
npm -g install homebridge-hubitat
`````

**Comment by jvmahon** [comment]
This is now working (version 0.0.9 and later), so I'm closing the issue.
Re-open if you find there  is still a problem
