### ISSUE TITLE
Hue Motion Sensor Temperature Sensor Incorrectly Displaying Temperature

### ISSUE THREAD

**Issue by barrysmartin** [jvmahon/homebridge-hubitat#7]
The temperature reading from Hue Motion Sensor coming over to Homebridge via Maker API is being represented in the logs properly in F however in the accessories it is being converted again to F like the temperature reading was in in C to begin with.  For example one reading reported into Homebridge as 72.31 degrees.  The accessory then displays the temperature as 163.78 degrees.  This is how it then shows up in Homekit as well.  This only happens on my Hue motion sensors and not the SmartThings ones, and it happens consistently on all of the Hue ones.

**Comment by jvmahon** [comment]
My guess is that the driver for your Hue sensors don't properly include the units when they report a temperature change - its something I've seen in other drivers. I've put a fix for that into the plugin. Update the plugin to version 0.0.9 and let me know if it now works.
`````
npm -g install homebridge-hubitat
`````

**Comment by barrysmartin** [comment]
Perfect!  Thank you so much!
