### ISSUE TITLE
Fan Service instead of Fanv2

### ISSUE THREAD

**Issue by drewcovi** [jvmahon/homebridge-hubitat#9]
Any chance we can tap into the Fan service rather than categorizing them as Fanv2? This opens up a few more icons in HomeKit, and a few more characteristics.

**Comment by drewcovi** [comment]
This may be a cached device issue

**Comment by drewcovi** [comment]
If this could at least be configurable, many zwave fan controls do not have extra parameters.

**Comment by jvmahon** [comment]
In the HomeKit Accessory Protocol Specification (Non-Commercial, Release R2), only the FanV2 is used (the document refers to the Service as the "Fan" service, but its actually FanV2 being used - see image below). I assume the old "Fan" service is now deprecated and being phased out. Given that the HAP specification only uses FanV2, my preference is to stick with that. 

![image](https://user-images.githubusercontent.com/15061942/97118536-d19aca80-16e0-11eb-88fd-95fc74700a73.png)

**Comment by drewcovi** [comment]
I’m surprised in that case that they’ve added icons for ceiling fans and pedestal fans but not for anything categorized fanv2

**Comment by jvmahon** [comment]
FYI - there was a major bug in the fan code which prevented the Home app from updating when the fan was turned on / off. You'll want to update to the latest version (1.0.2) to fix that.

**Comment by drewcovi** [comment]
@jvmahon appreciate the heads-up. I might just have to sync with your upstream branch since I really can't afford to have this plugin sending heading and cooling thresholds even when im not using auto mode. still seeing that output from homebridge (obviously no practical reason apple is doing that).

**Comment by drewcovi** [comment]
ill stay tuned for if/when you comment-back-in that quick mode check. 🙂
